export const buildInvoiceViewProps = ({
  onCancel,
  onShowDebt,
  onOpenDebtReceipt,
  onShowRecent,
  onShowTemplate,
  showNewTicket = true,
  invoice,
  draftCode,
  date,
  setDate,
  handleCancelTicket,
  handleNewTicket,
  items,
  totalQty,
  customerDebt,
  totals,
  customerId,
  setCustomerId,
  activeCustomers,
  customer,
  note,
  setNote,
  searchKeyword,
  setSearchKeyword,
  filteredQuick,
  handleQuickAdd,
  setSearchOpen,
  handleAddProduct,
  handlePrint,
  products,
  updateItem,
  removeItem,
  isEdit,
  payments,
  paymentModalOpen,
  setPaymentModalOpen,
  totalPayment,
  remainingPayment,
  paymentAmount,
  setPaymentAmount,
  paymentMethod,
  setPaymentMethod,
  paymentNote,
  setPaymentNote,
  handleCheckout,
  searchOpen,
  activeProducts,
  pendingProduct,
  pendingQty,
  pendingPrice,
  pendingLength,
  pendingWidth,
  handlePendingProductChange,
  pendingPreviousPrice,
  applyPendingPreviousPrice,
  setPendingQty,
  setPendingPrice,
  setPendingLength,
  setPendingWidth,
  handleConfirmAdd,
  previewOpen,
  setPreviewOpen,
  previewHtml,
  onSearchProducts,
  onCreateProduct,
  onProductCreated,
}) => {
  const headerProps = {
    onCancel,
    onPreview: () => setPreviewOpen(true),
    onShowDebt: () => onShowDebt?.(),
    onOpenPayment: () => setPaymentModalOpen(true),
    onOpenDebtReceipt: () => onOpenDebtReceipt?.(),
    showDebtReceipt: Boolean(onOpenDebtReceipt),
  };

  const topSectionProps = {
    code: invoice?.code || draftCode,
    date,
    onDateChange: (val) => setDate(val?.toISOString() || new Date().toISOString()),
    onCancelTicket: handleCancelTicket,
    onShowRecent: () => onShowRecent?.(),
    onNewTicket: handleNewTicket,
    showNewTicket,
    itemsCount: items.length,
    totalQty,
    customerDebt,
    total: totals.total,
    customerId,
    onCustomerChange: setCustomerId,
    customers: activeCustomers,
    customer,
    note,
    onNoteChange: setNote,
  };

  const searchProps = {
    searchKeyword,
    onSearchKeywordChange: setSearchKeyword,
    onPressEnter: handleQuickAdd,
    onOpenSearch: () => setSearchOpen(true),
    onPrint: handlePrint,
    onShowTemplate: () => onShowTemplate?.(),
    filteredQuick,
    onQuickSelect: handleAddProduct,
  };

  const itemsTableProps = {
    items,
    products,
    onUpdateItem: updateItem,
    onRemoveItem: removeItem,
  };

  const paymentsSectionProps = {
    isEdit,
    payments,
    changeLog: invoice?.changeLog || [],
  };

  const paymentModalProps = {
    open: paymentModalOpen,
    onClose: () => setPaymentModalOpen(false),
    customerName: customer?.name || 'Khách lẻ',
    total: totals.total,
    customerDebt,
    totalPayment,
    remainingPayment,
    paymentAmount,
    onPaymentAmountChange: setPaymentAmount,
    onPayFull: () => setPaymentAmount(totalPayment),
    paymentMethod,
    onPaymentMethodChange: setPaymentMethod,
    paymentNote,
    onPaymentNoteChange: setPaymentNote,
    onCheckoutPrint: () => handleCheckout(true),
    onCheckout: () => handleCheckout(false),
  };

  const productModalProps = {
    open: searchOpen,
    onClose: () => setSearchOpen(false),
    autoFocusSearchOnOpen: true,
    products: activeProducts,
    onSearchProducts,
    pendingProduct,
    pendingQty,
    pendingPrice,
    pendingLength,
    pendingWidth,
    previousPrice: pendingPreviousPrice,
    onChangeProduct: handlePendingProductChange,
    onChangeQty: setPendingQty,
    onChangePrice: setPendingPrice,
    onChangeLength: setPendingLength,
    onChangeWidth: setPendingWidth,
    onApplyPreviousPrice: applyPendingPreviousPrice,
    onConfirmAdd: handleConfirmAdd,
    onCreateProduct,
    onProductCreated,
  };

  const previewModalProps = {
    open: previewOpen,
    onClose: () => setPreviewOpen(false),
    html: previewHtml,
  };

  return {
    headerProps,
    topSectionProps,
    searchProps,
    itemsTableProps,
    paymentsSectionProps,
    paymentModalProps,
    productModalProps,
    previewModalProps,
  };
};
