import { createPersistInvoice } from './invoicePayload.js';
import { buildInvoiceViewProps } from './invoiceViewProps.js';
import { useInvoiceComputedState } from './hooks/useInvoiceComputedState.js';
import { useInvoiceDraftState } from './hooks/useInvoiceDraftState.js';
import { useInvoicePaymentFlow } from './hooks/useInvoicePaymentFlow.js';
import { useInvoicePreview } from './hooks/useInvoicePreview.js';
import { useInvoiceProductSelection } from './hooks/useInvoiceProductSelection.js';
import { useInvoiceTicketActions } from './hooks/useInvoiceTicketActions.js';

const useInvoiceEditorState = ({
  invoice,
  draftInvoice,
  customers = [],
  products = [],
  payments = [],
  allPayments = [],
  invoices = [],
  customerDebtOverride,
  settings,
  onSave,
  onAddPayment,
  onUpdatePayment,
  onRemovePayment,
  onCancel,
  onShowDebt,
  onOpenDebtReceipt,
  onShowRecent,
  onShowTemplate,
  onNewInvoice,
  onCustomerChange,
  onSearchProducts,
  onCreateProduct,
}) => {
  const isEdit = Boolean(invoice);
  const invoiceDraft = invoice || draftInvoice;
  const draft = useInvoiceDraftState({
    invoice: invoiceDraft,
    customers,
    onCustomerChange,
  });
  const computed = useInvoiceComputedState({
    customerId: draft.customerId,
    customers,
    products,
    payments,
    allPayments,
    invoices,
    invoice,
    items: draft.items,
    customerDebtOverride,
  });
  const productSelection = useInvoiceProductSelection({
    items: draft.items,
    setItems: draft.setItems,
    products,
    activeProducts: computed.activeProducts,
    onSearchProducts,
    getProductPrice: computed.getProductPrice,
    getPreviousProductPrice: computed.getPreviousProductPrice,
  });

  const persistInvoice = createPersistInvoice({
    onSave,
    invoice,
    items: draft.items,
    products,
    draftCode: draft.draftCode,
    customerId: draft.customerId,
    defaultCustomerId: draft.defaultCustomerId,
    date: draft.date,
    totals: computed.totals,
    status: computed.status,
    note: draft.note,
  });
  const ticketActions = useInvoiceTicketActions({
    invoice,
    onNewInvoice,
    defaultCustomerId: draft.defaultCustomerId,
    setItems: draft.setItems,
    setNote: draft.setNote,
    setPrintNote: draft.setPrintNote,
    setDate: draft.setDate,
    setDraftCode: draft.setDraftCode,
    setCustomerId: draft.setCustomerId,
    setSearchKeyword: productSelection.setSearchKeyword,
    setPendingProduct: productSelection.setPendingProduct,
    setPendingQty: productSelection.setPendingQty,
    setPendingPrice: productSelection.setPendingPrice,
    setPendingLength: productSelection.setPendingLength,
    setPendingWidth: productSelection.setPendingWidth,
  });
  const preview = useInvoicePreview({
    settings,
    invoice,
    items: draft.items,
    total: computed.totals.total,
    date: draft.date,
    draftCode: draft.draftCode,
    customerDebt: computed.customerDebt,
    printNote: draft.printNote,
    customer: computed.customer,
    payments,
    products,
  });
  const paymentFlow = useInvoicePaymentFlow({
    isEdit,
    paidTotal: computed.paidTotal,
    payments,
    onAddPayment,
    onUpdatePayment,
    onRemovePayment,
    customerDebt: computed.customerDebt,
    total: computed.totals.total,
    persistInvoice,
    handlePrint: preview.handlePrint,
    handleNewTicket: ticketActions.handleNewTicket,
  });

  return buildInvoiceViewProps({
    onCancel,
    onShowDebt,
    onOpenDebtReceipt,
    onShowRecent,
    onShowTemplate,
    showNewTicket: false,
    invoice,
    draftCode: draft.draftCode,
    date: draft.date,
    setDate: draft.setDate,
    handleCancelTicket: ticketActions.handleCancelTicket,
    handleNewTicket: ticketActions.handleNewTicket,
    items: draft.items,
    totalQty: computed.totalQty,
    customerDebt: computed.customerDebt,
    totals: computed.totals,
    customerId: draft.customerId,
    setCustomerId: draft.setCustomerId,
    activeCustomers: computed.activeCustomers,
    customer: computed.customer,
    note: draft.note,
    setNote: draft.setNote,
    printNote: draft.printNote,
    setPrintNote: draft.setPrintNote,
    searchKeyword: productSelection.searchKeyword,
    setSearchKeyword: productSelection.setSearchKeyword,
    filteredQuick: productSelection.filteredQuick,
    handleQuickAdd: productSelection.handleQuickAdd,
    setSearchOpen: productSelection.setSearchOpen,
    handleAddProduct: productSelection.handleAddProduct,
    handlePrint: preview.handlePrint,
    products,
    updateItem: productSelection.updateItem,
    removeItem: productSelection.removeItem,
    isEdit,
    payments,
    paymentModalOpen: paymentFlow.paymentModalOpen,
    setPaymentModalOpen: paymentFlow.setPaymentModalOpen,
    totalPayment: paymentFlow.totalPayment,
    remainingPayment: paymentFlow.remainingPayment,
    paymentAmount: paymentFlow.paymentAmount,
    setPaymentAmount: paymentFlow.setPaymentAmount,
    paymentMethod: paymentFlow.paymentMethod,
    setPaymentMethod: paymentFlow.setPaymentMethod,
    paymentNote: paymentFlow.paymentNote,
    setPaymentNote: paymentFlow.setPaymentNote,
    handleCheckout: paymentFlow.handleCheckout,
    searchOpen: productSelection.searchOpen,
    activeProducts: computed.activeProducts,
    pendingProduct: productSelection.pendingProduct,
    pendingQty: productSelection.pendingQty,
    pendingPrice: productSelection.pendingPrice,
    pendingLength: productSelection.pendingLength,
    pendingWidth: productSelection.pendingWidth,
    handlePendingProductChange: productSelection.handlePendingProductChange,
    pendingPreviousPrice: productSelection.pendingPreviousPrice,
    applyPendingPreviousPrice: productSelection.applyPendingPreviousPrice,
    setPendingQty: productSelection.setPendingQty,
    setPendingPrice: productSelection.setPendingPrice,
    setPendingLength: productSelection.setPendingLength,
    setPendingWidth: productSelection.setPendingWidth,
    handleConfirmAdd: productSelection.handleConfirmAdd,
    previewOpen: preview.previewOpen,
    setPreviewOpen: preview.setPreviewOpen,
    previewHtml: preview.previewHtml,
    onSearchProducts,
    onCreateProduct,
    onProductCreated: productSelection.handleProductCreated,
  });
};

export default useInvoiceEditorState;
